import turtle
gertrude = turtle.Turtle()
gertrude.forward(100)
gertrude.right(90)
gertrude.forward(50)
p = gertrude.position()
h = gertrude.heading()
print(p)
print(gertrude.xcor())
print(gertrude.ycor())
print(h)
